---

- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: install ansible prerequisites
    script: ansible_prereqs.sh creates=/root/.ansible_prereqs_installed
    register: ans_preq
    changed_when: "'CHANGE' in ans_preq.stdout"

- hosts: all
  become: true
  tags: [users]
  name: user setup
  roles:
  - role: systemuser
    user: hendrik



- hosts: all
  become: true
  name:  apps
  tasks:
  - name: update to latest apt
    apt: update_cache=yes upgrade=dist cache_valid_time=3600
  - name: adding the usefull apps
    apt: name={{item}} state=latest
    with_items:
      - sudo
      - lsof
      - tcpdump
      - sshguard
  - name: configure sudoers
    lineinfile: "dest=/etc/sudoers.d/ansible line='%sudo  ALL=(ALL) NOPASSWD: ALL' state=present create=yes validate='visudo -cf %s'"
